version: "3.8"
services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - n8n_network

  n8n:
    build: .
    restart: always
    ports:
      - "127.0.0.1:5678:5678"
    shm_size: '2g'
    env_file:
      - .env
    volumes:
      - ./n8n-workflows:/home/node/n8n/workflows
      - ./scripts:/home/node/scripts
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres
    networks:
      - n8n_network

volumes:
  postgres_data:
  n8n_data:

networks:
  n8n_network:
