
app = "naosite-leads-mdvmcg"

[build]
  dockerfile = "Dockerfile"

[env]
  # On dit juste à n8n où il est accessible publiquement. C'est tout.
  WEBHOOK_URL = "https://naosite-leads-mdvmcg.fly.dev"

[[mounts]]
  source      = "n8n_data"
  destination = "/root/.n8n"

[[services]]
  internal_port = 5678
  protocol      = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["http","tls"]
    port = 443
