app = "naosite-leads-mdvmcg"     # <- le nom exact de ton appli Fly

[build]
  dockerfile = "Dockerfile"      # indique à Fly d’utiliser ton Dockerfile

[[mounts]]
  source      = "n8n_data"
  destination = "/root/.n8n"
  
[[services]]
  internal_port = 5678           # port exposé par n8n
  protocol      = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["http","tls"]
    port = 443
    
WEBHOOK_URL = "https://naosite-leads-mdvmcg.fly.dev"
