app = "naosite-leads"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 5678
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
    
  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = "15s"
    timeout = "10s"
    grace_period = "5s"
    method = "get"
    path = "/healthz"
    protocol = "http"
    tls_skip_verify = false
