name: Deploy to Fly.io

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Chargement du binaire flyctl
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1   # ← nouveau repo / tag
        with:
          version: latest                               # optionnel : verrouille la version

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
