name: Deploy to Fly.io

# 1️⃣ – Déclencheurs
on:
  push:
    branches: [main]       # déploie à chaque push sur main
  workflow_dispatch:       # déclenchement manuel dans l’onglet Actions

# 2️⃣ – Un seul job
jobs:
  deploy:
    runs-on: ubuntu-latest

    # 3️⃣ – Variables d’environnement communes au job
    env:
      FLY_API_TOKEN:            ${{ secrets.FLY_API_TOKEN }}
      N8N_DEFAULT_USER_EMAIL:   ${{ secrets.N8N_DEFAULT_USER_EMAIL }}
      N8N_DEFAULT_USER_PASSWORD:${{ secrets.N8N_DEFAULT_USER_PASSWORD }}
      ENCRYPTION_KEY:           ${{ secrets.ENCRYPTION_KEY }}

    steps:
      # 4️⃣ – Récupération du code
      - name: Checkout
        uses: actions/checkout@v4

      # 5️⃣ – Installation de flyctl (action officielle)
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1   # une seule action suffit
        with:
          version: latest                               # verrouiller si besoin

      # 6️⃣ – (Optionnel) mise à jour des secrets côté Fly
      - name: Sync Fly secrets
        run: |
          flyctl secrets set \
            N8N_DEFAULT_USER_EMAIL="$N8N_DEFAULT_USER_EMAIL" \
            N8N_DEFAULT_USER_PASSWORD="$N8N_DEFAULT_USER_PASSWORD" \
            ENCRYPTION_KEY="$ENCRYPTION_KEY" \
            --app naosite-leads-mdvmcg --yes

      # 7️⃣ – Déploiement
      - name: Deploy app
        run: flyctl deploy --remote-only --app naosite-leads-mdvmcg
