name: Deploy to Fly.io

# 1️⃣ – Déclencheurs
on:
  push:
    branches: [main]       # déploie à chaque push sur main
  workflow_dispatch:       # déclenchement manuel dans l’onglet Actions

# 2️⃣ – Un seul job
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1
        with:
          version: latest

      # 1️⃣  On pousse/MAJ les secrets 
      - name: Set Fly secrets
        run: |
          flyctl secrets set \
            N8N_DEFAULT_USER_EMAIL="${{ secrets.N8N_DEFAULT_USER_EMAIL }}" \
            N8N_DEFAULT_USER_PASSWORD="${{ secrets.N8N_DEFAULT_USER_PASSWORD }}" \
            ENCRYPTION_KEY="${{ secrets.ENCRYPTION_KEY }}" \
            --app naosite-leads-mdvmcg --stage 
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      # 2️⃣  Puis on déploie, une seule ligne
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only --app naosite-leads-mdvmcg
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
