name: Deploy to Fly.io

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Chargement du binaire flyctl
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1   # ← nouveau repo / tag
        with:
          version: latest                               # optionnel : verrouille la version


name: Deploy to Fly.io
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-action@1.3
        with:
          args: deploy --remote-only --app naosite-leads-mdvmcg
        env:
          FLY_API_TOKEN:            ${{ secrets.FLY_API_TOKEN }}
          N8N_DEFAULT_USER_EMAIL:   ${{ secrets.N8N_DEFAULT_USER_EMAIL }}
          N8N_DEFAULT_USER_PASSWORD: ${{ secrets.N8N_DEFAULT_USER_PASSWORD }}
          ENCRYPTION_KEY:           ${{ secrets.ENCRYPTION_KEY }}
